app/urls.py
from django.conf.urls import url

from app import views
app_name='app'
urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),
    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='market_params'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 购物车页面
    url(r'^cart/', views.cart, name='cart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change_select_status'),

    # 下单
    url(r'^generateOrder/', views.generate_order, name='generate_order'),

    # 修改订单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 代付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 代付款订单支付
    url(r'^waitPayToPayed/', views.wait_pay_to_payed, name='wait_pay_to_payed'),

    # 全选
    url(r'^changeCartAllSelect/', views.change_cart_all_select, name='change_cart_all_select'),

    # 总价
    url(r'^countPrice/', views.count_price, name='count_price'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import static

from axf import settings

from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', views.home)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/common/functions.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">

                <ul>
                    <li>收货人:王帅帅<div><p><span><a href="#">修改&gt;</a></span></p></div></li>
                    <li>电话:8008208820 </li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        <!--购物车信息展示-->
                        {% csrf_token %}
                        {% for cart in user_carts %}
                            <li class="menuList" cartid="">
                                <div class="confirm">
                                    <span id="changeselect_{{ cart.id }}">
                                        {% if cart.is_select == 1 %}
                                            <span id="cart_id_{{ cart.id }}" onclick="changeSelectStatus({{ cart.id }});">√</span>
                                        {% else %}
                                            <span id="cart_id_{{ cart.id }}" onclick="changeSelectStatus({{ cart.id }});">x</span>
                                        {% endif %}

                                    </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.productimg }}" alt="">
                                    <p>{{ cart.goods.productlongname }}</p>
                                </a>
                                <section>
                                    <button onclick="subCart({{ cart.goods.id }})">-</button>
                                    <span id="num_{{ cart.goods.id }}">{{ cart.c_num }}</span>
                                    <button onclick="addCart({{ cart.goods.id }})">+</button>
                                </section>
                            </li>
                        {% endfor %}
                        <!--购物车数据处理结束-->


                        <li class="payTheBill">

                            <div class="confirm" onclick="all_select(1)" id="all_select_id">
                                <span>
                                    <span id="select_id">√</span>
                                </span>
                            </div>

                            <p>
                                <span>全选</span>
                                <span id="count_price">总价:</span>
                            </p>

                            <span><a href="{% url 'axf:generate_order' %}">下单</a></span>

                        </li>

                    </ul>

                </menu>

{#            <div class="menuList">#}
{##}
{#                {% for cart in carts %}#}
{##}
{#                    <div class="confirm">#}
{#                    <span>#}
{#                        <span>√</span>#}
{#                    </span>#}
{#                    </div>#}
{##}
{#                    <a href="#">#}
{#                        <img src="{{ cart.goods.productimg }}" alt="{{ cart.goods.productlongname }}">#}
{#                        <p>{{ cart.goods.productlongname }}</p>#}
{#                    </a>#}
{##}
{#                {% endfor %}#}
{##}
{##}
{#            </div>#}
            </section>



        </div>


    </div>


{% endblock %}