app/urls.py
from django.conf.urls import url

from app import views
app_name='app'
urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),
    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='market_params'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 购物车页面
    url(r'^cart/', views.cart, name='cart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change_select_status'),

    # 下单
    url(r'^generateOrder/', views.generate_order, name='generate_order'),

    # 修改订单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 代付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 代付款订单支付
    url(r'^waitPayToPayed/', views.wait_pay_to_payed, name='wait_pay_to_payed'),

    # 全选
    url(r'^changeCartAllSelect/', views.change_cart_all_select, name='change_cart_all_select'),

    # 总价
    url(r'^countPrice/', views.count_price, name='count_price'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import static

from axf import settings

from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', views.home)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block extCSS %}

    {% endblock %}
    <title>{{ title }}</title>
</head>
<body>

{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block EXTJS %}

{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}
{% block extCSS %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

{% endblock %}

{% block header %}

    <header></header>

{% endblock %}

{% block footer %}

    <footer>

        <a href="{% url 'axf:home' %}" class="home">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>

            </dl>

        </a>
        <a href="{% url 'axf:market' %}" class="market">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>

            </dl>

        </a>
        <a href="{% url 'axf:cart' %}" class="cart">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>

            </dl>

        </a>
        <a href="{% url 'axf:mine' %}" class="mine">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>

            </dl>

        </a>

    </footer>

{% endblock %}