app/urls.py
from django.conf.urls import url

from app import views
app_name='app'
urlpatterns = [
    # 首页
    url(r'^home/', views.home, name='home'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),
    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='market_params'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 购物车页面
    url(r'^cart/', views.cart, name='cart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change_select_status'),

    # 下单
    url(r'^generateOrder/', views.generate_order, name='generate_order'),

    # 修改订单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 代付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 代付款订单支付
    url(r'^waitPayToPayed/', views.wait_pay_to_payed, name='wait_pay_to_payed'),

    # 全选
    url(r'^changeCartAllSelect/', views.change_cart_all_select, name='change_cart_all_select'),

    # 总价
    url(r'^countPrice/', views.count_price, name='count_price'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import static

from axf import settings

from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', views.home)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from user.models import UserModel


class Main(models.Model):
    img = models.CharField(max_length=200)  # 图片
    name = models.CharField(max_length=100)  # 名称
    trackid = models.CharField(max_length=16)  # 通用id

    class Meta:
        abstract = True


class MainWheel(Main):
    # 轮循banner
    class Meta:
        db_table = "axf_wheel"


class MainNav(Main):
    # 导航
    class Meta:
        db_table = "axf_nav"


class MainMustBuy(Main):
    # 必购
    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):
    # 商店
    class Meta:
        db_table = 'axf_shop'


"""
insert into axf_mainshow
(trackid,name,img,categoryid,brandname,img1,childcid1,productid1,longname1,price1,marketprice1,
img2,childcid2,productid2,longname2,price2,marketprice2,img3,childcid3,productid3,longname3,price3,marketprice3)
 values("21782","优选水果","http://img01.bqstatic.com//upload/activity/2017031018205492.jpg@90Q.jpg",
 "103532","爱鲜蜂","http://img01.bqstatic.com/upload/goods/201/701/1916/20170119164159_996462.jpg@200w_200h_90Q",
 "103533","118824","爱鲜蜂·特小凤西瓜1.5-2.5kg/粒","25.80","25.8","http://img01.bqstatic.com/upload/goods/201/611/1617/20161116173544_219028.jpg@200w_200h_90Q",
 "103534","116950","蜂觅·越南直采红心火龙果350-450g/盒","15.3","15.8","http://img01.bqstatic.com/upload/goods/201/701/1916/20170119164119_550363.jpg@200w_200h_90Q",
 "103533","118826","爱鲜蜂·海南千禧果400-450g/盒","9.9","13.8");


"""

# 主要展示的商品
class MainShow(Main):
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)
    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = "axf_mainshow"


"""
        (typeid,typename,childtypenames,typesort)
"""
# 闪购--左侧类型表
class FoodType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_foodtypes"


"""
insert into axf_goods
(productid,productimg,productname,productlongname,isxf,pmdesc,specifics,price,marketprice,
categoryid,childcid,childcidname,dealerid,storenums,productnum) 
values("11951","http://img01.bqstatic.com/upload/goods/000/001/1951/0000011951_63930.jpg@200w_200h_90Q","",
"乐吧薯片鲜虾味50.0g",0,0,"50g",2.00,2.500000,103541,103543,"膨化食品","4858",200,4);
"""
class Goods(models.Model):
    productid = models.CharField(max_length=16)   # 商品的id
    productimg = models.CharField(max_length=200)   #商品的图片
    productname = models.CharField(max_length=100)   # 商品的名称
    productlongname = models.CharField(max_length=200)  # 商品的规格
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)   # 规格
    price = models.FloatField(default=0)   # 折后价格
    marketprice = models.FloatField(default=1)  #  原价
    categoryid = models.CharField(max_length=16)   # 分类id
    childcid = models.CharField(max_length=16)   # 子分类id
    childcidname = models.CharField(max_length=100)  # 名称
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)  #
    productnum = models.IntegerField(default=1)  # 销量排序

    class Meta:
        db_table = "axf_goods"


# 购物车
class CartModel(models.Model):
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE,)  # 关联用户
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,)  # 关联商品
    c_num = models.IntegerField(default=1)  # 商品的个数
    is_select = models.BooleanField(default=True)  #  是否选择商品

    class Meta:
        db_table = 'axf_cart'


class OrderModel(models.Model):
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE,)  # 关联用户
    o_num = models.CharField(max_length=64)  # 订单号
    # 0 代表已下单，但是未付款， 1 已付款未发货  2 已付款，已发货.....
    o_status = models.IntegerField(default=0)  # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE,)  # 关联的商品
    order = models.ForeignKey(OrderModel,on_delete=models.CASCADE,)  # 关联的订单
    goods_num = models.IntegerField(default=1)  # 商品的个数

    class Meta:
        db_table = 'axf_order_goods'

templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/common/functions.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">
    <!--订单编号-->
    <h3>订单编号: {{ order.o_num }}</h3>
    <!--处理结束-->
    <ul>
        {% for ordergoods in order.ordergoodsmodel_set.all %}
        <!--所有订单信息展示-->
            <li>
                <!--商品名称展示-->
                <img src="{{ ordergoods.goods.productimg }}">

                <span> <!-- 数量展示 -->{{ ordergoods.goods_num }}</span>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>
        {% csrf_token %}
        <!--订单id展示-->
        <button onclick="change_order({{ order.id }});" class="btn btn-success btn-block">
            Alipay
        </button>

    </div>


{% endblock %}

templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        <!--订单展示-->
        {% for order in orders %}
            <li>
                <a href="#">
                    <p><!-- 订单id -->{{ order.o_num }}</p>
                    <p><!-- 数量 --></p>
                        <!--展示商品的名称-->
                    {% for order_goods in order.ordergoodsmodel_set.all %}
                        <li>
                            <img src="{{ order_goods.goods.productimg }}" alt="">
                        </li>
                    {% endfor %}
                        <!--处理结束-->
                </a>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>


{% endblock %}

templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        <!--订单信息展示-->
        {% for order in orders %}
            <li>
                <a href="">
                    <p><!-- 订单id -->
                        <a href="{% url 'axf:wait_pay_to_payed' %}?order_id={{ order.id }}">
                            {{ order.o_num }}
                        </a>
                    </p>
                    <p><!-- 数量 --></p>
                    {% for order_goods in order.ordergoodsmodel_set.all %}
                        <!--展示商品的名称-->
                        <li>
                            <img src="{{ order_goods.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->
                    {% endfor %}
                </a>
            </li>
        <div style="height:10px; width:100%; border:6px solid #000000;"></div>
        {% endfor %}
        <!--订单处理结束-->


    </ul>


{% endblock %}